name: NHL - Games of Day

on:
  schedule:
    # Tous les jours Ã  04:00 UTC
    - cron: "0 4 * * *"
  workflow_dispatch: # Lancement manuel

jobs:
  run-nhl-games-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run NHL games of day script
        run: |
          python scripts/NHL/games_of_days_nhl.py

      - name: Commit updated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/hockey/games_of_day_nhl.json
          git commit -m "Update NHL games of the day" || echo "No changes to commit"
          git push